site_name: Документация к боту AFL-Ассистент
site_url: https://fbotru.github.io/public_docs/
theme:
  name: material
  font: false
  language: ru
  palette:
    - scheme: default
      primary: indigo        # основной цвет
      accent: deep purple    # цвет акцентов
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

  features:
    - header.autohide
    - navigation.tabs       # верхние вкладки
    - navigation.sections   # боковое меню для выбранной вкладки
    - navigation.top        # "вверх" в шапке
    - navigation.footer     # кнопки "предыдущая/следующая" внизу страниц

extra_css:
  - css/fonts.css

nav:
  - Добро пожаловать: index.md

  - Начало работы:
      - Основные функции: docs/1_users_mini.md
      - Регистрация: docs/users_mini/1_registration.md
      - Главное меню: docs/users_mini/2_main_menu.md
      - Профиль: docs/users_mini/3_user_profile.md
      - Оценка судей: docs/users_mini/4_rate_referee.md

  - Игроку клуба:
      - Обзор возможностей: docs/club_player/index.md
      - Тренировки: docs/club_player/trainings.md
      - Абонементы: docs/club_player/subscriptions.md
      - Оплата картой: docs/club_player/card_payment.md
      - Наличные и задолженности: docs/club_player/cash_and_debts.md
      - Статистика и рейтинги: docs/club_player/statistics.md

  - Капитану клуба:
      - Обзор возможностей: docs/club_captain/index.md
      - Подготовка командного чата: docs/club_captain/team_chat.md
      - Расписание и тренировки: docs/club_captain/trainings.md
      - Игроки и абонементы: docs/club_captain/players.md
      - Настройка оплат: docs/club_captain/payments.md
      - Долги и финансовый отчёт: docs/club_captain/finance.md
      - Уведомления: docs/club_captain/notifications.md
      - Команды, рейтинг и SMM: docs/club_captain/club_tools.md
